import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>My FLAN Q&A app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <textarea
          id=""
          name=""
          rows="28"
          cols="100"
          placeholder="Ask a question"
        ></textarea>
        <button>Submit</button>
      </main>
    </>
  );
}
